name: Reusable-workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: |
          echo ${{ inputs.username }}
          echo ${{ secrets.token }}
          echo ${{ username }}
          echo ${{ token }}
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}
